name: KioChatSpy
main: kiochatspy.KioChatSpy
version: 1.0.0
author: Kio
load: POSTWORLD
description: A Minecraft plugin to check local messages via console
commands:
  kcs:
    description: Main KioChatSpy command, use it to list sub-commands. 
    aliases: [kiochatspy]  
    usage: /<command>
permissions:
  kioantifly.use:
  kioantifly.*:
    description: Star notation of permissions, includes all of them.
    default: op
    children:
      kiochatspy.use: true